# Boilerplate from patrickloeber/python-github-action-template
name: Run daily website test python script

on:
  workflow_dispatch:
    
  # schedule:
  #   - cron: '0 8 */1 * *' # At 08:00 in morning, everyday of the month

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Selenium Tester for Chrome
        run: python selenium_tester.py --web-driver firefox --website ${{ secrets.WEBSITE }} --login-email ${{ secrets.LOGIN_EMAIL }} --login-password ${{ secrets.LOGIN_PASSWORD }} --recaptcha-enabled